config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"

  resources :solicitacao_repasses
  resources :sobreaviso_de_entregas

  resources :usuarios

  resources :entrega_internas
  resources :entrega_externas
  resources :encomendas

  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"

  root "sessions#new"
end

app/models/entrega_externa.rb
require "validates_timeliness"

class EntregaExterna < ApplicationRecord
  has_one :encomenda

  accepts_nested_attributes_for :encomenda, update_only: true

  validates :recebidoPor, presence: true, length: { maximum: 70 }
  validates_date :dataChegada, :before => Date.tomorrow, after_message: "A data de chegada está inválida. Datas futuras não são permitidas"
  validates_time :horaChegada, :between => "5:00am"..."7:00pm", invalid_time_message: "A hora de chegada está inválida. Selecione um horário entre 5:00 e 17:00"

  validates :encomenda, presence: true
end

app/controllers/entrega_externas_controller.rb
class EntregaExternasController < ApplicationController
  before_action :set_entrega_externa, only: %i[ show edit update destroy ]
  before_action :authorize

  # GET /entrega_externas or /entrega_externas.json
  def index
    @entrega_externas = EntregaExterna.all
  end

  # GET /entrega_externas/1 or /entrega_externas/1.json
  def show
  end

  # GET /entrega_externas/new
  def new
    @entrega_externa = EntregaExterna.new
    @entrega_externa.build_encomenda
  end

  # GET /entrega_externas/1/edit
  def edit
  end

  # POST /entrega_externas or /entrega_externas.json
  def create
    @entrega_externa = EntregaExterna.new(entrega_externa_params)

    respond_to do |format|
      if @entrega_externa.save
        format.html { redirect_to @entrega_externa, notice: "Entrega externa was successfully created." }
        format.json { render :show, status: :created, location: @entrega_externa }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @entrega_externa.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /entrega_externas/1 or /entrega_externas/1.json
  def update
    respond_to do |format|
      if @entrega_externa.update(entrega_externa_params)
        format.html { redirect_to @entrega_externa, notice: "Entrega externa was successfully updated." }
        format.json { render :show, status: :ok, location: @entrega_externa }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @entrega_externa.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /entrega_externas/1 or /entrega_externas/1.json
  def destroy
    @entrega_externa.destroy
    respond_to do |format|
      format.html { redirect_to entrega_externas_url, notice: "Entrega externa was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_entrega_externa
    @entrega_externa = EntregaExterna.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def entrega_externa_params
    params.require(:entrega_externa).permit(:dataChegada, :horaChegada, :recebidoPor, encomenda_attributes: [:peso, :remetente, :usuario_id])
  end
end

app/helpers/entrega_externas_helper.rb
module EntregaExternasHelper
end

app/views/entrega_externas/_form.html.erb
<body class="page">
<%= form_with(model: entrega_externa) do |form| %>
  <% if entrega_externa.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(entrega_externa.errors.count, "error") %> prohibited this entrega_externa from being saved:</h2>

      <ul>
        <% entrega_externa.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <h3> Dados sobre a encomenda </h3>

  <%= form.fields_for :encomenda do |encomenda_fields| %>
  <div class="field">
    <%= encomenda_fields.label :Peso %>
    <%= encomenda_fields.text_field :peso %>
  </div>

  <div class="field">
    <%= encomenda_fields.label :Remetente %>
    <%= encomenda_fields.text_field :remetente %>
  </div>

  <div class="field">
  <%= encomenda_fields.label :Destinatário %><br>
  <%= encomenda_fields.select(:usuario_id, Usuario.all.pluck(:nome, :id)) %>
</div>

  <% end %>

  <h3> Dados sobre a entrega </h3>

  <div class="field">
    <%= form.label :Data_da_chegada %>
    <%= form.date_select :dataChegada %>
  </div>

  <div class="field">
    <%= form.label :Hora_da_chegada %>
    <%= form.time_select :horaChegada %>
  </div>

  <div class="field">
    <%= form.label :Recebido_por %>
    <%= form.text_field :recebidoPor %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</body>

app/views/entrega_externas/edit.html.erb
<h1>Editing Entrega Externa</h1>

<%= render "form", entrega_externa: @entrega_externa %>

<%= link_to "Visualizar", @entrega_externa %> |
<%= link_to "Voltar", entrega_externas_path %>

app/views/entrega_externas/index.html.erb
<body class="page">
<p id="notice"><%= notice %></p>

<h1>Entrega Externas</h1>

<table cellpadding="0" border="0" align="center" cellspacing="0">
  <thead class="head_tabela">
    <tr>
      <th class="th">Datachegada</th>
      <th class="th">Horachegada</th>
      <th class="th">Recebidopor</th>
      <th class="th">Encomenda</th>
      <th class="th" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @entrega_externas.each do |entrega_externa| %>
      <tr>
        <td><%= entrega_externa.dataChegada %></td>
        <td><%= entrega_externa.horaChegada %></td>
        <td><%= entrega_externa.recebidoPor %></td>
        <td><%= link_to "Visualizar", entrega_externa %></td>
        <td><%= link_to "Editar", edit_entrega_externa_path(entrega_externa) %></td>
        <td><%= link_to "Marcar como entregue", new_entrega_interna_path(:entrega_externa_id => entrega_externa.id) %></td>
        <td><%= link_to "Excluir", entrega_externa, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Cadastrar entrega externa", new_entrega_externa_path %>

app/views/entrega_externas/new.html.erb
<h1>New Entrega Externa</h1>

<%= render 'form', entrega_externa: @entrega_externa %>

<%= link_to 'Back', entrega_externas_path %>

app/views/entrega_externas/show.html.erb
<body class="page">
<p id="notice"><%= notice %></p>

<div class="show">
<p>
  <strong>Datachegada:</strong>
  <%= @entrega_externa.dataChegada %>
</p>

<p>
  <strong>Horachegada:</strong>
  <%= @entrega_externa.horaChegada %>
</p>

<p>
  <strong>Recebidopor:</strong>
  <%= @entrega_externa.recebidoPor %>
</p>
</div>
<div>
<%= link_to 'Edit', edit_entrega_externa_path(@entrega_externa) %> |
<%= link_to 'Back', entrega_externas_path %>
</div>
</body>