config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"

  resources :solicitacao_repasses
  resources :sobreaviso_de_entregas

  resources :usuarios

  resources :entrega_internas
  resources :entrega_externas
  resources :encomendas

  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"

  root "sessions#new"
end

app/controllers/solicitacao_repasses_controller.rb
class SolicitacaoRepassesController < ApplicationController
  before_action :set_solicitacao_repasse, only: %i[ show edit update destroy ]
  before_action :authorize

  # GET /solicitacao_repasses or /solicitacao_repasses.json
  def index
    @solicitacao_repasses = SolicitacaoRepasse.all
    @solicitacoes = []
    @solicitacao_repasses.each { |solicitacao|
      @encomenda = EntregaExterna.find(params[:id], solicitacao.entrega_externa_id)
      if !@current_user.isMorador || @encomenda.encomenda.usuario.id == @current_user.id
        @solicitacoes.push(solicitacao)
      end
    }
    @solicitacao_repasses = @solicitacoes
  end

  # GET /solicitacao_repasses/1 or /solicitacao_repasses/1.json
  def show
  end

  # GET /solicitacao_repasses/new
  def new
    @solicitacao_repass = SolicitacaoRepasse.new
    @entregas_externas = EntregaExterna.all
    @entregas_externas_usuario = []
    @entregas_externas.each { |entrega|
      if !@current_user.isMorador || entrega.encomenda.usuario.id == @current_user.id
        @entregas_externas_usuario.push(entrega)
      end
    }
  end

  # GET /solicitacao_repasses/1/edit
  def edit
    @entregas_externas = EntregaExterna.all
    @entregas_externas_usuario = []
    @entregas_externas.each { |entrega|
      if !@current_user.isMorador || entrega.encomenda.usuario.id == @current_user.id
        @entregas_externas_usuario.push(entrega)
      end
    }
  end

  # POST /solicitacao_repasses or /solicitacao_repasses.json
  def create
    @solicitacao_repass = SolicitacaoRepasse.new(solicitacao_repasse_params)
    @entregas_externas = EntregaExterna.all
    @entregas_externas_usuario = []
    @entregas_externas.each { |entrega|
      if !@current_user.isMorador || entrega.encomenda.usuario.id == @current_user.id
        @entregas_externas_usuario.push(entrega)
      end
    }

    respond_to do |format|
      if @solicitacao_repass.save
        format.html { redirect_to @solicitacao_repass, notice: "Solicitacao repasse was successfully created." }
        format.json { render :show, status: :created, location: @solicitacao_repass }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @solicitacao_repass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /solicitacao_repasses/1 or /solicitacao_repasses/1.json
  def update
    respond_to do |format|
      if @solicitacao_repass.update(solicitacao_repasse_params)
        format.html { redirect_to @solicitacao_repass, notice: "Solicitacao repasse was successfully updated." }
        format.json { render :show, status: :ok, location: @solicitacao_repass }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @solicitacao_repass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /solicitacao_repasses/1 or /solicitacao_repasses/1.json
  def destroy
    @solicitacao_repass.destroy
    respond_to do |format|
      format.html { redirect_to solicitacao_repasses_url, notice: "Solicitacao repasse was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_solicitacao_repasse
    @solicitacao_repass = SolicitacaoRepasse.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def solicitacao_repasse_params
    params.require(:solicitacao_repasse).permit(:dataSolicitada, :entrega_externa_id)
  end
end

app/helpers/solicitacao_repasses_helper.rb
module SolicitacaoRepassesHelper
end

app/views/solicitacao_repasses/_form.html.erb
<body class="page">
<%= form_with(model: solicitacao_repass) do |form| %>
  <% if solicitacao_repass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(solicitacao_repass.errors.count, "error") %> prohibited this solicitacao_repass from being saved:</h2>

      <ul>
        <% solicitacao_repass.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Data_solicitada %>
    <%= form.date_select :dataSolicitada %>
  </div>

  <div class="field">
    <%= form.label :entrega_externa_id%>
    <%= form.select :entrega_externa_id, @entregas_externas_usuario.collect { |entrega| entrega.id } %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</body>

app/views/solicitacao_repasses/edit.html.erb
<h1>Editing Solicitacao Repass</h1>

<%= render 'form', solicitacao_repass: @solicitacao_repass %>

<%= link_to 'Show', @solicitacao_repass %> |
<%= link_to 'Back', solicitacao_repasses_path %>

app/views/solicitacao_repasses/index.html.erb
<body class="page">
<p id="notice"><%= notice %></p>

<h1>Solicitacao Repasses</h1>

<table cellpadding="0" border="0" align="center" cellspacing="0">
  <thead class="head_tabela">
    <tr>
      <th class="th">ID</th>
      <th class="th">Datasolicitada</th>
      <th class="th" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @solicitacao_repasses.each do |solicitacao_repass| %>
      <tr>
        <td class="td"><%= solicitacao_repass.id %></td>
        <td class="td"><%= solicitacao_repass.dataSolicitada %></td>
        <td class="td"><%= link_to "Show", solicitacao_repass %></td>
        <td class="td"><%= link_to "Edit", edit_solicitacao_repass_path(solicitacao_repass) %></td>
        <td class="td"><%= link_to "Destroy", solicitacao_repass, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "New Solicitacao Repass", new_solicitacao_repass_path %>
</body>

app/views/solicitacao_repasses/new.html.erb
<h1>Criar solicitação de repasse</h1>

<%= render "form", solicitacao_repass: @solicitacao_repass %>

<%= link_to "Voltar", solicitacao_repasses_path %>

app/views/solicitacao_repasses/show.html.erb
<body class="page">
<p id="notice"><%= notice %></p>

<div class="show">
<p>
  <strong>Datasolicitada:</strong>
  <%= @solicitacao_repass.dataSolicitada %>
</p>

<p>
  <strong>Entregaexterna:</strong>
  <%= @solicitacao_repass.entrega_externa_id %>
</p>

<%= link_to "Editar", edit_solicitacao_repass_path(@solicitacao_repass) %> |
<%= link_to "Voltar", solicitacao_repasses_path %>