config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"

  resources :solicitacao_repasses
  resources :sobreaviso_de_entregas

  resources :usuarios

  resources :entrega_internas
  resources :entrega_externas
  resources :encomendas

  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"

  root "sessions#new"
end

app/models/usuario.rb
require "cpf_cnpj"

class Usuario < ApplicationRecord
  has_many :encomendas, :dependent => :destroy
  has_many :sobreaviso_de_entregas, :dependent => :destroy

  has_secure_password

  validates :nome, presence: true, length: { minimum: 3, maximum: 75 }

  VALID_EMAIL_FORMAT = /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i
  validates :email, presence: true, length: { maximum: 260 }, format: { with: VALID_EMAIL_FORMAT },
                    uniqueness: { case_sensitive: false }

  validates :telefone, presence: true, format: { with: /\A\d+\z/, message: "is invalid" }

  validates :cpf, presence: true, uniqueness: true
  validate :valid_cpf?

  validates :numero_residencia, presence: true, numericality: { only_integer: true, :greater_than_or_equal_to => 1 },
                                format: { with: /\A\d+\z/, message: "Apenas carcteres numéricos são aceitos nesse campo." }

  validates :bloco_residencia, presence: true, numericality: { only_integer: true, :greater_than_or_equal_to => 1 },
                               format: { with: /\A\d+\z/, message: "Apenas carcteres numéricos são aceitos nesse campo." }

  validates :password, presence: true, length: { minimum: 6 }

  def valid_cpf?
    unless CPF.valid?(self.cpf)
      errors.add(:cpf, "invalid")
    end
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :authorize
  before_action :set_usuario, only: %i[ show edit update destroy ]

  # GET /usuarios or /usuarios.json
  def index
    if !current_user_morador?()
      if params[:isMorador]
        @usuarios = Usuario.where(:isMorador => params[:isMorador])
      else
        @usuarios = Usuario.all
      end
    else
      @usuarios = Usuario.where("id = ?", current_user.id)
    end
  end

  # GET /usuarios/1 or /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios or /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: "Usuario was successfully created." }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1 or /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: "Usuario was successfully updated." }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1 or /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: "Usuario was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_usuario
    @usuario = Usuario.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def usuario_params
    params.require(:usuario).permit(:nome, :email, :telefone, :cpf, :numero_residencia, :bloco_residencia, :isMorador, :password, :password_confirmation)
  end
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/usuarios/_form.html.erb
<body class="page">
<%= form_with(model: usuario) do |form| %>
  <% if usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
        <% usuario.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :Email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :Senha %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :Confirmação_de_senha %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :Telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="field">
    <%= form.label :CPF %>
    <%= form.text_field :cpf %>
  </div>

  <div class="field">
    <%= form.label :Numero_de_residencia %>
    <%= form.number_field :numero_residencia %>
  </div>

  <div class="field">
    <%= form.label :Bloco_da_residencia %>
    <%= form.number_field :bloco_residencia %>
  </div>


    <div class="field">
      <%= form.label :Morador, "É um morador?" %>
      <%= form.select :isMorador, ["Sim", "Nao"] %>
    </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
</body>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<body class="page">
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table cellpadding="0" border="0" align="center" cellspacing="0">
  <thead class="head_tabela">
    <tr>
      <th class="th">Nome</th>
      <th class="th">Email</th>
      <th class="th">Telefone</th>
      <th class="th">Cpf</th>
      <th class="th">Numero residencia</th>
      <th class="th">Bloco residencia</th>
      <th class="th" colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td class="td"><%= usuario.nome %></td>
        <td class="td"><%= usuario.email %></td>
        <td class="td"><%= usuario.telefone %></td>
        <td class="td"><%= usuario.cpf %></td>
        <td class="td"><%= usuario.numero_residencia %></td>
        <td class="td"><%= usuario.bloco_residencia %></td>
        <td class="td"><%= link_to "Visualizar", usuario %></td>
        <td class="td"><%= link_to "Editar", edit_usuario_path(usuario) %></td>
        <td class="td"><%= link_to "Excluir", usuario, method: :delete, data: { confirm: "Are you sure?" } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to "Cadastrar novo usuario", new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>Cadastrar usuario</h1>

<%= render "form", usuario: @usuario %>

<% if logged_in? %>
    <%= link_to "Voltar", usuarios_path %>
<% else %>
<%= link_to "Voltar", root_path %>
<% end %>

app/views/usuarios/show.html.erb
<body class="page">
<p id="notice"><%= notice %></p>

<div class="show">
<p>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</p>

<p>
  <strong>Email:</strong>
  <%= @usuario.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @usuario.telefone %>
</p>

<p>
  <strong>CPF:</strong>
  <%= @usuario.cpf %>
</p>

<p>
  <strong>Numero residencia:</strong>
  <%= @usuario.numero_residencia %>
</p>

<p>
  <strong>Bloco residencia:</strong>
  <%= @usuario.bloco_residencia %>
</p>

<%= link_to "Editar", edit_usuario_path(@usuario) %> |
<%= link_to "Voltar", encomendas_path %>