config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"

  resources :solicitacao_repasses
  resources :sobreaviso_de_entregas

  resources :usuarios

  resources :entrega_internas
  resources :entrega_externas
  resources :encomendas

  get "sign_in" => "sessions#new"
  post "sign_in" => "sessions#create"
  delete "sign_out" => "sessions#destroy"

  root "sessions#new"
end

app/models/encomenda.rb
class Encomenda < ApplicationRecord
  belongs_to :usuario
  belongs_to :entrega_externa

  validates :peso, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
  validates :remetente, presence: true, length: { minimum: 3, maximum: 75 }

  validates :entrega_externa, presence: true
  validates :usuario, presence: true
end

app/controllers/encomendas_controller.rb
class EncomendasController < ApplicationController
  before_action :current_user_morador?
  before_action :set_encomenda, only: %i[ show edit update destroy ]
  before_action :correct_user?, only: [:destroy, :show]
  before_action :authorize

  # GET /encomendas or /encomendas.json
  def index
    if !current_user_morador?()
      @encomendas = Encomenda.all
    else
      @encomendas = Encomenda.where("usuario_id = ?", current_user)
    end
  end

  # GET /encomendas/1 or /encomendas/1.json
  def show
  end

  # GET /encomendas/new
  def new
    @encomenda = Encomenda.new
  end

  # GET /encomendas/1/edit
  def edit
  end

  # POST /encomendas or /encomendas.json
  def create
    @encomenda = Encomenda.new(encomenda_params)

    respond_to do |format|
      if @encomenda.save
        format.html { redirect_to @encomenda, notice: "Encomenda was successfully created." }
        format.json { render :show, status: :created, location: @encomenda }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @encomenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /encomendas/1 or /encomendas/1.json
  def update
    respond_to do |format|
      if @encomenda.update(encomenda_params)
        format.html { redirect_to @encomenda, notice: "Encomenda was successfully updated." }
        format.json { render :show, status: :ok, location: @encomenda }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @encomenda.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /encomendas/1 or /encomendas/1.json
  def destroy
    @encomenda.destroy
    respond_to do |format|
      format.html { redirect_to encomendas_url, notice: "Encomenda was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_encomenda
    @encomenda = Encomenda.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def encomenda_params
    params.require(:encomenda).permit(:peso, :remetente, :usuario_id)
  end
end

app/helpers/encomendas_helper.rb
module EncomendasHelper
end

app/views/encomendas/_form.html.erb
<body class="page">
<%= form_with(model: encomenda) do |form| %>
  <% if encomenda.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(encomenda.errors.count, "error") %> prohibited this encomenda from being saved:</h2>

      <ul>
        <% encomenda.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Peso %>
    <%= form.text_field :peso %>
  </div>

  <div class="field">
    <%= form.label :Remetente %>
    <%= form.text_field :remetente %>
  </div>

  <div class="field">
    <%= form.label :usuario_id %>
    <%= form.text_field :usuario_id %>
  </div>

  <div class="actions" >
    <%= form.submit %>
  </div>
<% end %>
</body>

app/views/encomendas/edit.html.erb
<h1>Editing Encomenda</h1>

<%= render "form", encomenda: @encomenda %>

<%= link_to "Visualizar", @encomenda %> |
<%= link_to "Voltar", encomendas_path %>

app/views/encomendas/index.html.erb
<body class="page">
<p id="notice"><%= notice %></p>

<h1>Encomendas - Entregas externas</h1>

<table cellpadding="0" border="0" align="center" cellspacing="0">
  <thead class="head_tabela">
    <tr>
      <th class="th">ID</th>
      <th class="th">Peso</th>
      <th class="th">Remetente</th>
      <th class="th">Morador</th>
      <th class="th">Data de chegada</th>
      <th class="th">Recebido por</th>
      <th class="th" colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @encomendas.each do |encomenda| %>
      <tr>
        <td class="td"><%= encomenda.id %></td>
        <td class="td"><%= encomenda.peso %></td>
        <td class="td"><%= encomenda.remetente %></td>
        <td class="td"><%= encomenda.usuario.try(:nome) %> </td>
        <td class="td"><%= encomenda.entrega_externa.try(:dataChegada) %></td>
        <td class="td"><%= encomenda.entrega_externa.try(:recebidoPor) %></td>

        <td class="td"><%= link_to "Visualizar", encomenda %></td>

        <% if !current_user_morador?() %>
          <td class="td"><%= link_to "Marcar como entregue", new_entrega_interna_path(:entrega_externa_id => encomenda.entrega_externa.try(:id)) %></td>
          <td class="td"><%= link_to "Editar", edit_entrega_externa_path(encomenda) %></td>
          <td class="td"><%= link_to "Deletar", encomenda, method: :delete, data: { confirm: "Are you sure?" } %></td>
        <% end %>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>
</body>

app/views/encomendas/new.html.erb
<h1>New Encomenda</h1>

<%= render 'form', encomenda: @encomenda %>

<%= link_to 'Back', encomendas_path %>

app/views/encomendas/show.html.erb
<body class="page">
<p id="notice"><%= notice %></p>

<div class="show">
<p>
  <strong>Peso:</strong>
  <%= @encomenda.peso %>
</p>

<p>
  <strong>Remetente:</strong>
  <%= @encomenda.remetente %>
</p>

<p>
  <strong>Morador:</strong>
  <%= @encomenda.usuario_id %>
</p>

<p>
  <strong>Data de chegada:</strong>
  <%= @encomenda.entrega_externa.dataChegada %>
</p>

<p>
  <strong>Hora de chegada:</strong>
  <%= @encomenda.entrega_externa.horaChegada %>
</p>

<p>
  <strong>Recebido por:</strong>
  <%= @encomenda.entrega_externa.recebidoPor %>
</p>
</div>

<div>
<% if !current_user_morador?() %>
  <%= link_to "Editar", edit_encomenda_path(@encomenda) %> |
<% end %>

<%= link_to "Voltar", encomendas_path %>
</div>

</body>